# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80f09876c5d8b10bde79cbb5cbf144f24d16fb5bb462ff4297d766a3e8b3449f0d3859b737fffda5b21fbf4bac8b76594f757334dccbdcfc64c70fb7021ce9a9

test:
  secret_key_base: 8c5afd07b5d52339fb24ef678ad707c874a16cd3bc1f3a7f52fee82e87bc24ce387a210e334d08c1f13a3a9079ab86e757634bec556b9ef5beddca3411a22985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
